spring.application.name=Imanager

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_2p5OvmOJoeVZPSqJfz2@mysql-32c2a6f9-anujawij-8f00.h.aivencloud.com:16850/Imanager_db?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_2p5OvmOJoeVZPSqJfz2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
